@echo off
echo Cleaning git cache...
git rm -r --cached vendor
git rm -r --cached node_modules
echo Adding files...
git add .
echo Committing...
git commit -m "chore: remove vendor and node_modules from tracking"
echo Pushing...
git push origin main --force
echo Done.
